const C3 = globalThis.C3;

C3.Plugins.Azerion_Integration_SDK.Acts =
{
	InitializeSDK()
	{
		this._initializeSDK();
	},
	OnLoadStart()
	{
		this._onLoadStart();
	},
	OnLoadProgress(progress)
	{
		this._onLoadProgress(progress);
	},
	OnLoadComplete()
	{
		this._onLoadComplete();
	},
	AddListeners()
	{
		this._addListeners();
	},
	OnAdProviderLoaded()
	{
		this._onAdProviderLoaded();
	},
	OnGameStart()
	{
		this._onGameStart();
	},
	OnGameEnd()
	{
		this._onGameEnd();
	},
	ShowInterstitialAd()
	{
		this._showInterstitialAd();
	},
	ShowRewardedAd()
	{
		this._showRewardedAd();
	},
	PreloadAd(type)
	{
		this._preloadAd(type);
	},
	SendScoreEvent(score, level, cummulativeScore, gameTitle, platformId) 
	{
		this._sendScoreEvent(score, level, cummulativeScore, gameTitle, platformId);
	},
	PauseAdTimer()
	{
		this._pauseAdTimer();
	},
	ResumeAdTimer()
	{
		this._resumeAdTimer();
	}
};
