const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.Turret,
		C3.Behaviors.Timer,
		C3.Plugins.Azerion_Integration_SDK,
		C3.Plugins.Text,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Esplashqky_Event1_Act4,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.JavaScriptInEvents.Esplashqky_Event1_Act9,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.JavaScriptInEvents.Emenu_Event2_Act3,
		C3.Plugins.Azerion_Integration_SDK.Cnds.IsAdPlaying,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Arr.Acts.Clear,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Behaviors.Turret.Acts.SetRange,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.Turret.Cnds.HasTarget,
		C3.Behaviors.Turret.Exps.TargetUID,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Behaviors.custom.Cnds.CompareSpeed,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Azerion_Integration_SDK.Acts.InitializeSDK,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.Azerionintegration_Event3_Act7,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadProgress,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadComplete,
		C3.Plugins.Azerion_Integration_SDK.Acts.AddListeners,
		C3.JavaScriptInEvents.Azerionintegration_Event8_Act2,
		C3.JavaScriptInEvents.Azerionintegration_Event8_Act3,
		C3.Plugins.Azerion_Integration_SDK.Acts.PreloadAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowInterstitialAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowRewardedAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameEnd,
		C3.JavaScriptInEvents.Azerionintegration_Event22_Act1,
		C3.JavaScriptInEvents.Azerionintegration_Event22_Act3,
		C3.JavaScriptInEvents.Azerionintegration_Event23_Act2,
		C3.JavaScriptInEvents.Azerionintegration_Event23_Act3,
		C3.Plugins.Audio.Acts.SetSilent
	];
};
self.C3_JsPropNameTable = [
	{LocalStorage: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{AJAX: 0},
	{PlatformInfo: 0},
	{Anchor: 0},
	{Game_Tittle: 0},
	{show: 0},
	{ScrollTo: 0},
	{men_manager: 0},
	{ZombieSign: 0},
	{paused: 0},
	{win: 0},
	{defeat: 0},
	{nWave: 0},
	{totlives: 0},
	{lives: 0},
	{ntuto: 0},
	{coins: 0},
	{arrowkills: 0},
	{bombkills: 0},
	{sniperkills: 0},
	{electrickills: 0},
	{raypower: 0},
	{bombpower: 0},
	{gamemanager: 0},
	{goGame: 0},
	{Fade: 0},
	{Sine: 0},
	{taptoplay: 0},
	{ui_level: 0},
	{line_ui: 0},
	{casilla: 0},
	{Shrub: 0},
	{Tree: 0},
	{Wall: 0},
	{Wire: 0},
	{Grid: 0},
	{Stone: 0},
	{Box: 0},
	{Tin: 0},
	{FadeIn: 0},
	{Tween: 0},
	{backgroundbar: 0},
	{base_tower_create: 0},
	{base_tower_help: 0},
	{power: 0},
	{bgTutoNewPower: 0},
	{towerindex: 0},
	{BoundToLayout: 0},
	{bgUpdateTower: 0},
	{damage: 0},
	{zoneID: 0},
	{emiter: 0},
	{smoke: 0},
	{accurancy: 0},
	{Custom: 0},
	{Bomb: 0},
	{btnBomb: 0},
	{btnClose: 0},
	{btnCreateTower: 0},
	{btnRay: 0},
	{btnSell: 0},
	{btnSettings: 0},
	{btnTowerArcher: 0},
	{btnTowerBomb: 0},
	{btnTowerRay: 0},
	{btnTowerShooter: 0},
	{btnUpdate: 0},
	{buttonIndex: 0},
	{buildTower: 0},
	{Finish: 0},
	{FadeOut: 0},
	{hand: 0},
	{house: 0},
	{light: 0},
	{MoneyBuyUpdate: 0},
	{MoneyIG: 0},
	{MP: 0},
	{Direction: 0},
	{Index: 0},
	{Path: 0},
	{PointToDefend: 0},
	{PowerBombLoading: 0},
	{PowerRayLoading: 0},
	{ray: 0},
	{ray_selection: 0},
	{ray_small: 0},
	{rocks: 0},
	{hp: 0},
	{HealthBar: 0},
	{nIndex: 0},
	{direction: 0},
	{nextindex: 0},
	{spawner: 0},
	{Rotate: 0},
	{tnt: 0},
	{FadeInOut: 0},
	{warning: 0},
	{wave_complete: 0},
	{WaveBar: 0},
	{WaveIcon: 0},
	{ui_bghp: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{star_selector_nivel: 0},
	{star_selector: 0},
	{alert: 0},
	{roadSelector: 0},
	{bgStarsSelector: 0},
	{LevelSelectorTittle: 0},
	{bgSelector: 0},
	{dragging: 0},
	{topLimit: 0},
	{startX: 0},
	{tower_help_level: 0},
	{Bullet: 0},
	{cam_selector: 0},
	{txtBtnNivel: 0},
	{name: 0},
	{txtUI: 0},
	{txtUIArco: 0},
	{txtZombieDamage: 0},
	{Variables: 0},
	{Waves: 0},
	{TowerArcherDescription: 0},
	{TowerBombDescription: 0},
	{TowerSniperDescription: 0},
	{TowerElectricDescription: 0},
	{btnCredits: 0},
	{btnMoreGames: 0},
	{btnPlay: 0},
	{btnBack: 0},
	{btnMenu: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{btnUpgrade: 0},
	{btnHelp: 0},
	{btnCont: 0},
	{btnReset: 0},
	{btnParlante: 0},
	{QkyGamesLogo: 0},
	{bgCredits: 0},
	{BombsIconWin: 0},
	{ArcherIconWin: 0},
	{MagicalIconWin: 0},
	{SniperIconWin: 0},
	{win_stars: 0},
	{winTitle: 0},
	{win_boms_icon: 0},
	{shockwave: 0},
	{electric_particle: 0},
	{confettiWin: 0},
	{fadeSubMenu: 0},
	{tnt_particle: 0},
	{shockwave_arrow: 0},
	{shockwave_bomb: 0},
	{confettiExplosion: 0},
	{bomb_selection: 0},
	{BoomExplosion: 0},
	{cloud_particles: 0},
	{cloud_particles_small: 0},
	{DeadZombie: 0},
	{explosion: 0},
	{floor_particles: 0},
	{ray_particle: 0},
	{smoke_particle: 0},
	{Sprite: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Grass1: 0},
	{Grass12: 0},
	{Grass17: 0},
	{Grass18: 0},
	{Grass2: 0},
	{Grass11: 0},
	{Grass8: 0},
	{Grass9: 0},
	{Grass13: 0},
	{Grass14: 0},
	{Grass15: 0},
	{Grass16: 0},
	{Grass3: 0},
	{Grass4: 0},
	{Grass5: 0},
	{Grass6: 0},
	{Road: 0},
	{Grass7: 0},
	{Grass10: 0},
	{fire: 0},
	{Turret: 0},
	{Archer: 0},
	{targetID: 0},
	{endX: 0},
	{endY: 0},
	{createsmoke: 0},
	{Timer: 0},
	{Arrow: 0},
	{ArrowFloor: 0},
	{target: 0},
	{shock: 0},
	{ElectricBullet: 0},
	{open_updates: 0},
	{price: 0},
	{level: 0},
	{tower: 0},
	{ElectricTower: 0},
	{SniperBullet: 0},
	{SniperIG: 0},
	{target_arrow: 0},
	{target_electric: 0},
	{TowerArcher: 0},
	{posX: 0},
	{posY: 0},
	{TowerBomber: 0},
	{TowerSniper: 0},
	{targetBombs: 0},
	{archer_help: 0},
	{bgHelpDetail: 0},
	{tower_level: 0},
	{current_help: 0},
	{bgHelp: 0},
	{nLevel: 0},
	{CircleLevelHelp: 0},
	{towername: 0},
	{HelpButtonTower: 0},
	{sniper_help: 0},
	{tower_archer_help: 0},
	{tower_bomb_help: 0},
	{tower_electric_help: 0},
	{tower_sniper_help: 0},
	{bgSettings: 0},
	{bgSettings1: 0},
	{tittleDefeat: 0},
	{bgDefeat: 0},
	{healthstart: 0},
	{health: 0},
	{targetIndex: 0},
	{movementSpeed: 0},
	{randomDist: 0},
	{lasthit: 0},
	{offsetbarY: 0},
	{zOrder: 0},
	{fly: 0},
	{hitMin: 0},
	{hitMax: 0},
	{zombie1: 0},
	{zombie2: 0},
	{zombie3: 0},
	{zombie4: 0},
	{zombie5: 0},
	{zombie6: 0},
	{zombie7: 0},
	{zombie8: 0},
	{UpdateFillBarr: 0},
	{UpgradeButtonTower: 0},
	{lineMasc: 0},
	{iconUpgrades: 0},
	{bgUpgradePoints: 0},
	{update_feature: 0},
	{btnMoreUpdate: 0},
	{IconUpdateTop: 0},
	{tower_name: 0},
	{bgUpdateSelector: 0},
	{bgUpgradeCount: 0},
	{AzIntegrationPlugin: 0},
	{LoadingText: 0},
	{Buttons: 0},
	{SineElements: 0},
	{Pathfinding: 0},
	{Zombies: 0},
	{Towers: 0},
	{LoadProg: 0},
	{AllAssetsLoaded: 0},
	{dy: 0},
	{velY: 0},
	{dx: 0},
	{velX: 0},
	{xStart: 0},
	{yStart: 0},
	{xEnd: 0},
	{yEnd: 0},
	{flytime: 0},
	{towerlevel: 0},
	{nCant: 0},
	{totStars: 0},
	{star: 0},
	{score: 0},
	{Level: 0},
	{PriceTowerArcher: 0},
	{PriceTowerBomber: 0},
	{PriceTowerSniper: 0},
	{PriceTowerElectric: 0},
	{UpgradeFactor: 0},
	{BoosterX: 0},
	{BoosterY: 0},
	{buttonUI: 0},
	{towerUI: 0},
	{cant: 0},
	{mag: 0},
	{tiempo: 0},
	{uid: 0},
	{type: 0},
	{waveIndex: 0},
	{endWave: 0},
	{Audio_Enabled: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{layer: 0},
	{cantidad: 0},
	{newColor: 0},
	{angleToTarget: 0},
	{Gravity: 0},
	{offsetX: 0},
	{offsetY: 0},
	{HasFocus: 0},
	{rewardAvailable: 0},
	{IsWatchAd: 0},
	{PREROLL_ENABLED: 0},
	{progress: 0}
];

self.InstanceType = {
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	men_manager: class extends self.ISpriteInstance {},
	ZombieSign: class extends self.ISpriteInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	ui_level: class extends self.ISpriteInstance {},
	line_ui: class extends self.ISpriteInstance {},
	casilla: class extends self.ISpriteInstance {},
	Shrub: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Wire: class extends self.ISpriteInstance {},
	Grid: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Tin: class extends self.ISpriteInstance {},
	backgroundbar: class extends self.ISpriteInstance {},
	base_tower_create: class extends self.ISpriteInstance {},
	base_tower_help: class extends self.ISpriteInstance {},
	bgTutoNewPower: class extends self.ISpriteInstance {},
	bgUpdateTower: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	btnBomb: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnCreateTower: class extends self.ISpriteInstance {},
	btnRay: class extends self.ISpriteInstance {},
	btnSell: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	btnTowerArcher: class extends self.ISpriteInstance {},
	btnTowerBomb: class extends self.ISpriteInstance {},
	btnTowerRay: class extends self.ISpriteInstance {},
	btnTowerShooter: class extends self.ISpriteInstance {},
	btnUpdate: class extends self.ISpriteInstance {},
	buildTower: class extends self.ISpriteInstance {},
	Finish: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	house: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	MoneyBuyUpdate: class extends self.ISpriteInstance {},
	MoneyIG: class extends self.ISpriteInstance {},
	MP: class extends self.ISpriteInstance {},
	Path: class extends self.ISpriteInstance {},
	PointToDefend: class extends self.ISpriteInstance {},
	PowerBombLoading: class extends self.ITiledBackgroundInstance {},
	PowerRayLoading: class extends self.ITiledBackgroundInstance {},
	ray: class extends self.ISpriteInstance {},
	ray_selection: class extends self.ISpriteInstance {},
	ray_small: class extends self.ISpriteInstance {},
	rocks: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ITiledBackgroundInstance {},
	spawner: class extends self.ISpriteInstance {},
	tnt: class extends self.ISpriteInstance {},
	warning: class extends self.ISpriteInstance {},
	wave_complete: class extends self.ISpriteInstance {},
	WaveBar: class extends self.ISpriteInstance {},
	WaveIcon: class extends self.ISpriteInstance {},
	ui_bghp: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	star_selector_nivel: class extends self.ISpriteInstance {},
	star_selector: class extends self.ISpriteInstance {},
	alert: class extends self.ISpriteInstance {},
	roadSelector: class extends self.ISpriteInstance {},
	bgStarsSelector: class extends self.ISpriteInstance {},
	LevelSelectorTittle: class extends self.ISpriteInstance {},
	bgSelector: class extends self.ISpriteInstance {},
	cam_selector: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	txtUIArco: class extends self.ISpriteFontInstance {},
	txtZombieDamage: class extends self.ISpriteFontInstance {},
	Variables: class extends self.IArrayInstance {},
	Waves: class extends self.IArrayInstance {},
	TowerArcherDescription: class extends self.IArrayInstance {},
	TowerBombDescription: class extends self.IArrayInstance {},
	TowerSniperDescription: class extends self.IArrayInstance {},
	TowerElectricDescription: class extends self.IArrayInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnUpgrade: class extends self.ISpriteInstance {},
	btnHelp: class extends self.ISpriteInstance {},
	btnCont: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnParlante: class extends self.ISpriteInstance {},
	QkyGamesLogo: class extends self.ISpriteInstance {},
	bgCredits: class extends self.ISpriteInstance {},
	BombsIconWin: class extends self.ISpriteInstance {},
	ArcherIconWin: class extends self.ISpriteInstance {},
	MagicalIconWin: class extends self.ISpriteInstance {},
	SniperIconWin: class extends self.ISpriteInstance {},
	win_stars: class extends self.ISpriteInstance {},
	winTitle: class extends self.ISpriteInstance {},
	win_boms_icon: class extends self.ISpriteInstance {},
	shockwave: class extends self.ISpriteInstance {},
	electric_particle: class extends self.ISpriteInstance {},
	confettiWin: class extends self.ISpriteInstance {},
	fadeSubMenu: class extends self.ISpriteInstance {},
	tnt_particle: class extends self.ISpriteInstance {},
	shockwave_arrow: class extends self.ISpriteInstance {},
	shockwave_bomb: class extends self.ISpriteInstance {},
	confettiExplosion: class extends self.ISpriteInstance {},
	bomb_selection: class extends self.ISpriteInstance {},
	BoomExplosion: class extends self.ISpriteInstance {},
	cloud_particles: class extends self.ISpriteInstance {},
	cloud_particles_small: class extends self.ISpriteInstance {},
	DeadZombie: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	floor_particles: class extends self.IParticlesInstance {},
	ray_particle: class extends self.IParticlesInstance {},
	smoke_particle: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Grass1: class extends self.ISpriteInstance {},
	Grass12: class extends self.ISpriteInstance {},
	Grass17: class extends self.ISpriteInstance {},
	Grass18: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	Grass11: class extends self.ISpriteInstance {},
	Grass8: class extends self.ISpriteInstance {},
	Grass9: class extends self.ISpriteInstance {},
	Grass13: class extends self.ISpriteInstance {},
	Grass14: class extends self.ISpriteInstance {},
	Grass15: class extends self.ISpriteInstance {},
	Grass16: class extends self.ISpriteInstance {},
	Grass3: class extends self.ISpriteInstance {},
	Grass4: class extends self.ISpriteInstance {},
	Grass5: class extends self.ISpriteInstance {},
	Grass6: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	Grass7: class extends self.ISpriteInstance {},
	Grass10: class extends self.ISpriteInstance {},
	Archer: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	ArrowFloor: class extends self.ISpriteInstance {},
	ElectricBullet: class extends self.ISpriteInstance {},
	ElectricTower: class extends self.ISpriteInstance {},
	SniperBullet: class extends self.ISpriteInstance {},
	SniperIG: class extends self.ISpriteInstance {},
	target_arrow: class extends self.ISpriteInstance {},
	target_electric: class extends self.ISpriteInstance {},
	TowerArcher: class extends self.ISpriteInstance {},
	TowerBomber: class extends self.ISpriteInstance {},
	TowerSniper: class extends self.ISpriteInstance {},
	targetBombs: class extends self.ISpriteInstance {},
	archer_help: class extends self.ISpriteInstance {},
	bgHelpDetail: class extends self.ISpriteInstance {},
	bgHelp: class extends self.ISpriteInstance {},
	CircleLevelHelp: class extends self.ISpriteInstance {},
	HelpButtonTower: class extends self.ISpriteInstance {},
	sniper_help: class extends self.ISpriteInstance {},
	tower_archer_help: class extends self.ISpriteInstance {},
	tower_bomb_help: class extends self.ISpriteInstance {},
	tower_electric_help: class extends self.ISpriteInstance {},
	tower_sniper_help: class extends self.ISpriteInstance {},
	bgSettings: class extends self.ISpriteInstance {},
	bgSettings1: class extends self.ISpriteInstance {},
	tittleDefeat: class extends self.ISpriteInstance {},
	bgDefeat: class extends self.ISpriteInstance {},
	zombie1: class extends self.ISpriteInstance {},
	zombie2: class extends self.ISpriteInstance {},
	zombie3: class extends self.ISpriteInstance {},
	zombie4: class extends self.ISpriteInstance {},
	zombie5: class extends self.ISpriteInstance {},
	zombie6: class extends self.ISpriteInstance {},
	zombie7: class extends self.ISpriteInstance {},
	zombie8: class extends self.ISpriteInstance {},
	UpdateFillBarr: class extends self.ISpriteInstance {},
	UpgradeButtonTower: class extends self.ISpriteInstance {},
	lineMasc: class extends self.ISpriteInstance {},
	iconUpgrades: class extends self.ISpriteInstance {},
	bgUpgradePoints: class extends self.ISpriteInstance {},
	btnMoreUpdate: class extends self.ISpriteInstance {},
	IconUpdateTop: class extends self.ISpriteInstance {},
	bgUpdateSelector: class extends self.ISpriteInstance {},
	bgUpgradeCount: class extends self.ISpriteInstance {},
	AzIntegrationPlugin: class extends C3.Plugins.Azerion_Integration_SDK.Instance {},
	LoadingText: class extends self.ITextInstance {},
	Buttons: class extends self.ISpriteInstance {},
	SineElements: class extends self.ISpriteInstance {},
	Zombies: class extends self.ISpriteInstance {},
	Towers: class extends self.ISpriteInstance {}
}