name: Build Jekyll Chirpy Blog

on:
  push:
    paths:
      - 'blog/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies and build
        working-directory: blog
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build --baseurl "/blog"

      - name: Move built blog to blog-html
        run: |
          rm -rf blog-html
          mv blog/_site blog-html
